name: Deploy Team 8 Backend to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (for lint/test, optional)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive project files
        run: |
          tar czf app.tar.gz --exclude='.git' --exclude='*.tar.gz' .

      - name: Copy files to AWS server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "app.tar.gz"
          target: "/home/ubuntu/nodeapps/2025/flight-plan/t8"

      - name: Deploy on AWS server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/nodeapps/2025/flight-plan/t8
            tar xzf app.tar.gz
            rm app.tar.gz
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
            sudo systemctl restart flight-plan-t8-backend.service
            sudo systemctl status flight-plan-t8-backend.service --no-pager
